//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Project Item Template</summary>
	[PublishedModel("projectItemTemplate")]
	public partial class ProjectItemTemplate : PublishedContentModel, IOurProjects, ISidebarItem
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "projectItemTemplate";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<ProjectItemTemplate, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public ProjectItemTemplate(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Calender Icon
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("calenderIcon")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CalenderIcon => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "calenderIcon");

		///<summary>
		/// Layout
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("layout")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockGridModel Layout => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockGridModel>(_publishedValueFallback, "layout");

		///<summary>
		/// Page Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageContent")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString PageContent => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "pageContent");

		///<summary>
		/// Position To The Left
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[ImplementPropertyType("positionToTheLeft")]
		public virtual bool PositionToTheLeft => this.Value<bool>(_publishedValueFallback, "positionToTheLeft");

		///<summary>
		/// Position To The Right
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[ImplementPropertyType("positionToTheRight")]
		public virtual bool PositionToTheRight => this.Value<bool>(_publishedValueFallback, "positionToTheRight");

		///<summary>
		/// Project Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectLink")]
		public virtual string ProjectLink => this.Value<string>(_publishedValueFallback, "projectLink");

		///<summary>
		/// Project Link Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectLinkText")]
		public virtual string ProjectLinkText => this.Value<string>(_publishedValueFallback, "projectLinkText");

		///<summary>
		/// Project Preamble
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectPreamble")]
		public virtual string ProjectPreamble => this.Value<string>(_publishedValueFallback, "projectPreamble");

		///<summary>
		/// Project Published
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectPublished")]
		public virtual string ProjectPublished => this.Value<string>(_publishedValueFallback, "projectPublished");

		///<summary>
		/// Project Thumbnail Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectThumbnailImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectThumbnailImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "projectThumbnailImage");

		///<summary>
		/// Project Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectTitle")]
		public virtual string ProjectTitle => this.Value<string>(_publishedValueFallback, "projectTitle");

		///<summary>
		/// Button Link Text: Our Projects
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("buttonLinkText")]
		public virtual string ButtonLinkText => global::Umbraco.Cms.Web.Common.PublishedModels.OurProjects.GetButtonLinkText(this, _publishedValueFallback);

		///<summary>
		/// Footer Background Color: Our Projects
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerBackgroundColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor FooterBackgroundColor => global::Umbraco.Cms.Web.Common.PublishedModels.OurProjects.GetFooterBackgroundColor(this, _publishedValueFallback);

		///<summary>
		/// Footer Subtitle: Our Projects
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerSubtitle")]
		public virtual string FooterSubtitle => global::Umbraco.Cms.Web.Common.PublishedModels.OurProjects.GetFooterSubtitle(this, _publishedValueFallback);

		///<summary>
		/// Footer Title: Our Projects
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerTitle")]
		public virtual string FooterTitle => global::Umbraco.Cms.Web.Common.PublishedModels.OurProjects.GetFooterTitle(this, _publishedValueFallback);

		///<summary>
		/// Headline: Our Projects
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headline")]
		public virtual string Headline => global::Umbraco.Cms.Web.Common.PublishedModels.OurProjects.GetHeadline(this, _publishedValueFallback);

		///<summary>
		/// Image Description: Our Projects
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("imageDescription")]
		public virtual string ImageDescription => global::Umbraco.Cms.Web.Common.PublishedModels.OurProjects.GetImageDescription(this, _publishedValueFallback);

		///<summary>
		/// IsExternal: Our Projects
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[ImplementPropertyType("isExternal")]
		public virtual bool IsExternal => global::Umbraco.Cms.Web.Common.PublishedModels.OurProjects.GetIsExternal(this, _publishedValueFallback);

		///<summary>
		/// Project Image: Our Projects
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("projectImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProjectImage => global::Umbraco.Cms.Web.Common.PublishedModels.OurProjects.GetProjectImage(this, _publishedValueFallback);

		///<summary>
		/// Section Title: Our Projects
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sectionTitle")]
		public virtual string SectionTitle => global::Umbraco.Cms.Web.Common.PublishedModels.OurProjects.GetSectionTitle(this, _publishedValueFallback);

		///<summary>
		/// Background Color Support
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backgroundColorSupport")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor BackgroundColorSupport => global::Umbraco.Cms.Web.Common.PublishedModels.SidebarItem.GetBackgroundColorSupport(this, _publishedValueFallback);

		///<summary>
		/// Form Email Input
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("formEmailInput")]
		public virtual string FormEmailInput => global::Umbraco.Cms.Web.Common.PublishedModels.SidebarItem.GetFormEmailInput(this, _publishedValueFallback);

		///<summary>
		/// Form Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("formHeadline")]
		public virtual string FormHeadline => global::Umbraco.Cms.Web.Common.PublishedModels.SidebarItem.GetFormHeadline(this, _publishedValueFallback);

		///<summary>
		/// Form Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("formText")]
		public virtual string FormText => global::Umbraco.Cms.Web.Common.PublishedModels.SidebarItem.GetFormText(this, _publishedValueFallback);

		///<summary>
		/// Sidebar Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sidebarHeadline")]
		public virtual string SidebarHeadline => global::Umbraco.Cms.Web.Common.PublishedModels.SidebarItem.GetSidebarHeadline(this, _publishedValueFallback);

		///<summary>
		/// Sidebar Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sidebarImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SidebarImage => global::Umbraco.Cms.Web.Common.PublishedModels.SidebarItem.GetSidebarImage(this, _publishedValueFallback);

		///<summary>
		/// Sidebar Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sidebarText")]
		public virtual string SidebarText => global::Umbraco.Cms.Web.Common.PublishedModels.SidebarItem.GetSidebarText(this, _publishedValueFallback);

		///<summary>
		/// Tag Items
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagItems")]
		public virtual global::System.Collections.Generic.IEnumerable<string> TagItems => global::Umbraco.Cms.Web.Common.PublishedModels.SidebarItem.GetTagItems(this, _publishedValueFallback);

		///<summary>
		/// Tag Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tagTitle")]
		public virtual string TagTitle => global::Umbraco.Cms.Web.Common.PublishedModels.SidebarItem.GetTagTitle(this, _publishedValueFallback);
	}
}
